all: ARTHEVAL_LEFT_ASSOCIATIVE.out

ARTHEVAL_LEFT_ASSOCIATIVE.out:	ARTHEVAL_LEFT_ASSOCIATIVE.cpp	eval.cpp
	g++ -o ARTHEVAL_LEFT_ASSOCIATIVE.out ARTHEVAL_LEFT_ASSOCIATIVE.cpp eval.cpp

clean:
	rm -f ARTHEVAL_LEFT_ASSOCIATIVE.out 
